### ISSUE TITLE
steps to get output

### ISSUE THREAD

**Issue by chahalmanisha** [earthat/VANET-Simulation-in-MATLAB#1]
In evaluation.m function [E,pcktlossrate,total_dist,pcktloss,thrgput]=evaluation(nodtble,node_rsu) what will be the value of nodtble and node_rsu or where we have to pass input parameters?

**Comment by earthat** [comment]
these input are passed from anish.m and parameters of nodes and RSU are updated in every iteration and passed to this function.

**Comment by chahalmanisha** [comment]
Could u please tell me the complete steps to run this project?

**Comment by earthat** [comment]
you need to just run anish.m

**Comment by Harshith7016** [comment]
Thank you sir for the code but i keep on getting error related to no nodes found run again....would you help me out in that sir

**Comment by earthat** [comment]
for less number of nodes or small transmission range, it may not work. Check out the parameters used in this video
https://www.youtube.com/watch?v=2QeSYOgJo9s&t=32s

**Comment by Harshith7016** [comment]
Thank you for providing the information

**Comment by Harshith7016** [comment]
Good evening sir,
I used the exact same parameters such as source node, destination node,
number of nodes still left with number of errors. I am still in the process
of understanding the code that is being written and would be really happy
if I am helped out in these errors.


Error using cellfun
Undefined function 'equal' for input arguments of type 'double'.

Error in UrbanCitySimu (line 174)
                dst_cell=find(cellfun(@equal,
str,repmat({dst_node},1,length(str)))); % find out whihch structre cell has
                destination node

Error in anish>Simulate_Callback (line 99)
[distance,energy,nw_liftime,throughput]=UrbanCitySimu(NumOfNodes,src_node,dst_node);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in anish (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)anish('Simulate_Callback',hObject,eventdata,guidata(hObject))
Error while evaluating UIControl Callback

Thank You.

**Comment by earthat** [comment]
@Harshith7016 , I updated the repository with a function equal.m. It was not uploaded earlier

**Comment by Harshith7016** [comment]
Sorry to interrupt again sir, but  http://free-thesis.com/2017/04/14/vanet-simulation-in-matlab/  this page is not found, it would be helpful if I get access to the information 
Thank You.

**Comment by earthat** [comment]
it is down and under construction again

**Comment by Harshith7016** [comment]
Hello sir, I would really appreciate if I get the opportunity to go through the paper once and under the concept behind few algorithms.... Thank You.

**Comment by earthat** [comment]
I don't have any single paper, bunch of random papers to study all these.
