### ISSUE TITLE
problem about representation of result

### ISSUE THREAD

**Issue by lidaryani** [earthat/VANET-Simulation-in-MATLAB#2]
hi,i have some problems about this program.as i see your sharing video in youtube my u=output is not like yours.
could you please help me to fix it?
![image](https://user-images.githubusercontent.com/23069766/48404225-0ce69d80-e745-11e8-88dc-b7f6ca7010ac.png)

**Comment by earthat** [comment]
Hi, I can see two issues in operation of this code by you:
1. The GUI is closed during the execution due to which figure is shown this way.
2. The number of nodes entered must be checked for optimal operation. It is not suitable for very few number of nodes.

**Comment by earthat** [comment]
You can also check out [this previous issue](https://github.com/earthat/VANET-Simulation-in-MATLAB/issues/1#issuecomment-380174370)

**Comment by lidaryani** [comment]
My problem was resolved by using last issue .Thank you very much for replying.
